name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 'install yarn'
      run: npm install -g yarn
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install --check-files
        gem install pg -v '1.1.4' --source 'https://rubygems.org/'
        bundle exec rake
